"use strict";

const V2_NAMESPACE = "donbeolja_v2";
const V2_EXCHANGE = "BINANCEFUT";
const V2_COLLECTION_PREFIX = `${V2_NAMESPACE}__`;

const V2_COLLECTIONS = Object.freeze({
  POSITION_CYCLES: "position_cycles_v2",
  CANONICAL_EXIT_TRANSITIONS: "canonical_exit_transitions_v2",
  EXIT_RUNTIME_PROJECTIONS: "exit_runtime_projection_v2",
  PROTECTION_RUNTIME: "protection_runtime_v2",
  TRADE_ALERT_OUTBOX: "trade_alert_outbox_v2",
  REPAIR_REQUESTS: "exit_repair_requests_v2",
  REPAIR_EXECUTION_LEDGER: "repair_execution_ledger_v2",
  SIGNAL_INTENTS: "signal_intents_v2",
  ML_AI_SIGNAL_PROPOSALS: "ml_ai_signal_proposals_v2",
  FEATURE_SNAPSHOTS: "feature_snapshots_v2",
  ML_AI_EVIDENCE_LEDGER: "ml_ai_evidence_ledger_v2",
  OPENCLAW_DECISIONS: "openclaw_decisions_v2",
  OPENCLAW_DECISION_BUNDLES: "openclaw_decision_bundles_v2",
  OPENCLAW_EXECUTION_AUDITS: "openclaw_execution_audits_v2",
  OPENCLAW_EXECUTION_CLAIMS: "openclaw_execution_claims_v2",
  OPENCLAW_WORLD_STATES: "openclaw_world_states_v2",
  OPENCLAW_EXECUTION_PERMITS: "openclaw_execution_permits_v2",
  OPENCLAW_OUTCOME_ADJUDICATIONS: "openclaw_outcome_adjudications_v2",
  OPENCLAW_LEARNER_SHADOW_EVALUATIONS: "openclaw_learner_shadow_evaluations_v2",
  TRAIL_OBSERVATIONS: "trail_observations_v2",
  LIQUIDATION_SNAPSHOTS: "liquidation_snapshots_v2",
  PRODUCTION_ENTRY_ROUTE_CANARIES: "production_entry_route_canaries_v2",
  EXIT_RUNTIME_CANARIES: "exit_runtime_canaries_v2",
  ACTIVE_PROTECTION_RECONCILIATIONS: "active_protection_reconciliations_v2",
});

const V2_SERVICES = Object.freeze({
  OPENCLAW_CONTROL_PLANE: "V2_OPENCLAW_CONTROL_PLANE",
  SIGNAL_AUTHORITY_ROUTER: "V2_SIGNAL_AUTHORITY_ROUTER",
  ML_AI_SIGNAL_ENGINE: "V2_ML_AI_SIGNAL_ENGINE",
  ENTRY_EXECUTOR: "V2_ENTRY_EXECUTOR",
  PROTECTION_WRITER: "V2_PROTECTION_WRITER",
  USER_TRADE_SYNC: "V2_USER_TRADE_SYNC",
  CANONICAL_EXIT_REDUCER: "V2_CANONICAL_EXIT_REDUCER",
  TICK_EXIT_WORKER: "V2_TICK_EXIT_WORKER",
  WATCHDOG: "V2_WATCHDOG",
  REPAIR_EXECUTOR: "V2_REPAIR_EXECUTOR",
  ALERT_WORKER: "V2_ALERT_WORKER",
});

const V2_EXIT_STAGES = Object.freeze([
  "PRE_TP1",
  "TP1_DONE",
  "TRAIL_ACTIVE",
  "EXITED_SL",
  "EXITED_TRAIL",
  "EXITED_EXTERNAL",
  "EXITED_MANUAL",
]);

const V2_TRANSITION_EVENTS = Object.freeze([
  "TP1_REACHED",
  "TRAIL_ACTIVATED",
  "SL_HIT",
  "TRAIL_HIT",
  "EXTERNAL_CLOSE_SYNC",
  "MANUAL_CLOSE_SYNC",
]);

const V2_HEALTH_STATUSES = Object.freeze([
  "HEALTHY",
  "DEGRADED_REPAIRABLE",
  "DEGRADED_UNPROTECTED",
  "TERMINAL_EXITED",
]);

const V2_POSITION_CYCLE_STATUSES = Object.freeze([
  "PROTECTION_PENDING",
  "ACTIVE_PROTECTED",
  "ACTIVE",
  "CLOSED",
]);

const V2_ALERT_TYPES = Object.freeze([
  "EXIT_TRANSITION_ALERT",
  "EXIT_PROTECTION_ALERT",
  "EXIT_REPAIR_ALERT",
]);

const V2_ALERT_STATUSES = Object.freeze([
  "PENDING",
  "SENT",
  "FAILED",
]);

const V2_SIGNAL_SOURCE_MODES = Object.freeze([
  "WEBHOOK_ASSISTED",
  "SERVER_NATIVE_ML_AI",
  "OPENCLAW_RECOMMENDED",
]);

const V2_DECISION_MODES = Object.freeze([
  "SHADOW",
  "PAPER",
  "CANARY",
  "LIVE",
]);

const V2_SIGNAL_DECISION_STATUSES = Object.freeze([
  "APPROVED",
  "BLOCKED",
  "SHADOW_ONLY",
]);

const V2_ML_AI_PROPOSAL_VERDICTS = Object.freeze([
  "PASS",
  "BLOCK",
  "SHADOW",
]);

const V2_RISK_BANDS = Object.freeze([
  "LOW",
  "MEDIUM",
  "HIGH",
]);

const V2_STRATEGY_FILTERS = Object.freeze([
  "HTF_DIRECTION_ALIGNMENT",
]);

const V2_STRATEGY_FILTER_VERDICTS = Object.freeze([
  "PASS",
  "BLOCK",
  "SHADOW",
]);

const V2_HARD_GUARDS = Object.freeze([
  "BUDGET_MIN_ORDER",
  "ENTRY_LINEAGE_REQUIRED",
  "EXCHANGE_PROTECTION_HEALTH",
]);

const V2_REDUCER_EVIDENCE_KINDS = Object.freeze([
  "TP1_CONFIRMED",
  "TRAIL_ACTIVATION_CONFIRMED",
  "STOP_EXIT_CONFIRMED",
  "EXTERNAL_CLOSE_CONFIRMED",
  "MANUAL_CLOSE_CONFIRMED",
]);

const V2_WATCHDOG_ISSUE_CODES = Object.freeze([
  "TP1_ORDER_MISSING",
  "NATIVE_REFRESH_UNHEALTHY",
  "TRAIL_STOP_MISSING",
  "UNPROTECTED_ACTIVE_POSITION",
  "TERMINAL_TRANSITION_MISSING",
  "TERMINAL_PROJECTION_MISMATCH",
  "TERMINAL_STAGE_WITH_ACTIVE_POSITION",
]);

const V2_REPAIR_ACTIONS = Object.freeze([
  "ENSURE_TP1_ORDER",
  "REFRESH_NATIVE_STOP",
  "ENSURE_FULL_PROTECTION",
]);

const V2_REPAIR_EXECUTION_STATUSES = Object.freeze([
  "DELEGATED",
  "SKIPPED",
  "COMPLETED_SUCCESS",
  "COMPLETED_FAILED",
]);

module.exports = {
  V2_NAMESPACE,
  V2_EXCHANGE,
  V2_COLLECTION_PREFIX,
  V2_COLLECTIONS,
  V2_SERVICES,
  V2_EXIT_STAGES,
  V2_TRANSITION_EVENTS,
  V2_HEALTH_STATUSES,
  V2_POSITION_CYCLE_STATUSES,
  V2_ALERT_TYPES,
  V2_ALERT_STATUSES,
  V2_SIGNAL_SOURCE_MODES,
  V2_DECISION_MODES,
  V2_SIGNAL_DECISION_STATUSES,
  V2_ML_AI_PROPOSAL_VERDICTS,
  V2_RISK_BANDS,
  V2_STRATEGY_FILTERS,
  V2_STRATEGY_FILTER_VERDICTS,
  V2_HARD_GUARDS,
  V2_REDUCER_EVIDENCE_KINDS,
  V2_WATCHDOG_ISSUE_CODES,
  V2_REPAIR_ACTIONS,
  V2_REPAIR_EXECUTION_STATUSES,
};
