const CHARTER_EXPECTATIONS = {
  signal_engine: {
    default: {
      SL: -0.015,
      TP_P0: 0.008,
      TP_P0_QTY: 0.25,
      TP_P0_ATR_MULTIPLE: 0.8,
      TP_P1: 0.03,
      TP_P1_RESCUE_COHORT: 0.0165,
      TP_P1_MIXED_COHORT: 0.025,
      TP_P1_QTY: 0.3,
      TP_C: null,
      BE_PCT: null,
      PRE_TP1_TIME_STOP_BARS_EARLY: 4,
      PRE_TP1_TIME_STOP_BARS_CORE: 6,
      PRE_TP1_TIME_STOP_PROGRESS_FRACTION: 0.5,
      TRAIL_DELAY_BARS: 1,
      TRAIL_DELAY_MFE_PCT: 0.005,
      TRAIL_R_MULTIPLE: 1.0,
      TRAIL_PCT: 0.015,
    },
    by_exchange: {
      UPBIT: {
        SL: -0.015,
        TP_P0: 0.008,
        TP_P0_QTY: 0.25,
        TP_P0_ATR_MULTIPLE: 0.8,
        TP_P1: 0.03,
        TP_P1_RESCUE_COHORT: 0.0165,
        TP_P1_MIXED_COHORT: 0.025,
        TP_P1_QTY: 0.3,
        TP_C: null,
        BE_PCT: null,
        PRE_TP1_TIME_STOP_BARS_EARLY: 4,
        PRE_TP1_TIME_STOP_BARS_CORE: 6,
        PRE_TP1_TIME_STOP_PROGRESS_FRACTION: 0.5,
        TRAIL_DELAY_BARS: 1,
        TRAIL_DELAY_MFE_PCT: 0.005,
        TRAIL_R_MULTIPLE: 1.0,
        TRAIL_PCT: 0.015,
      },
      BINANCEFUT: {
        SL: -0.0165,
        TP_P0: 0.008,
        TP_P0_QTY: 0.25,
        TP_P0_ATR_MULTIPLE: 0.8,
        TP_P1: 0.0325,
        TP_P1_RESCUE_COHORT: 0.0165,
        TP_P1_MIXED_COHORT: 0.025,
        TP_P1_QTY: 0.5,
        TP_C: null,
        BE_PCT: 0.0025,
        PRE_TP1_TIME_STOP_BARS_EARLY: 4,
        PRE_TP1_TIME_STOP_BARS_CORE: 6,
        PRE_TP1_TIME_STOP_PROGRESS_FRACTION: 0.5,
        TRAIL_DELAY_BARS: 1,
        TRAIL_DELAY_MFE_PCT: 0.005,
        TRAIL_R_MULTIPLE: 0.9,
        TRAIL_PCT: 0.01,
      },
      KIWOOM: {
        SL: -0.03,
        TP_P0: 0.008,
        TP_P0_QTY: 0.25,
        TP_P0_ATR_MULTIPLE: 0.8,
        TP_P1: 0.05,
        TP_P1_RESCUE_COHORT: 0.05,
        TP_P1_MIXED_COHORT: 0.05,
        TP_P1_QTY: 0.5,
        TP_C: null,
        BE_PCT: null,
        PRE_TP1_TIME_STOP_BARS_EARLY: 4,
        PRE_TP1_TIME_STOP_BARS_CORE: 6,
        PRE_TP1_TIME_STOP_PROGRESS_FRACTION: 0.5,
        TRAIL_DELAY_BARS: 1,
        TRAIL_DELAY_MFE_PCT: 0.005,
        TRAIL_R_MULTIPLE: 1.0,
        TRAIL_PCT: 0.03,
      },
    },
  },
  mapping: {
    SIGNAL_MAPPING_VERSION: "v1",
  },
};

module.exports = { CHARTER_EXPECTATIONS };
