"use strict";

const TRACE_KEYS = Object.freeze([
  "_live_exec_policy_stage",
  "_live_exec_policy_reason",
  "_live_exec_policy_market",
  "_live_exec_policy_action",
  "_live_exec_policy_allocation_score",
  "_live_exec_policy_quarantine_reason",
  "_live_exec_policy_quality_latency_ms",
  "_live_exec_policy_quality_partial_pct",
  "_live_exec_policy_quality_slippage_bps",
  "_live_exec_policy_quality_global_status",
  "_live_exec_policy_quality_global_latency_p95_ms",
  "_live_exec_policy_quality_global_partial_pct",
  "_live_exec_policy_quality_global_slippage_p95_bps",
  "_live_exec_policy_lineage_slo_enabled",
  "_live_exec_policy_lineage_slo_fail_closed",
  "_live_exec_policy_lineage_intents_signal_doc_id_null_rate",
  "_live_exec_policy_lineage_fills_signal_doc_id_null_rate",
  "_live_exec_policy_lineage_fills_intent_id_null_rate",
  "_live_exec_policy_lineage_entry_fills_intent_id_null_rate",
  "_live_exec_policy_lineage_entry_fills_24h_n",
  "_live_exec_policy_lineage_has_entry_fill_intent_metric",
  "_live_exec_policy_lineage_reason_suppressed",
  "_live_exec_policy_drift_remediation_enabled",
  "_live_exec_policy_other_server_policy_watch_only_block_enabled",
  "_live_exec_policy_other_server_policy_watch_only_block",
  "_live_exec_policy_other_server_policy_watch_only_market",
  "_live_exec_policy_other_server_policy_watch_only_reasons",
  "_live_exec_policy_plan_enabled",
  "_live_exec_policy_plan_apply",
  "_live_exec_policy_plan_status",
  "_live_exec_policy_plan_mode",
  "_live_exec_policy_plan_global_scale",
  "_live_exec_policy_plan_market_scale",
  "_live_exec_policy_learning_epoch_active",
  "_live_exec_policy_learning_epoch_exception_release_enabled",
  "_live_exec_policy_learning_epoch_exception_release_active",
  "_live_exec_policy_objective_scale",
  "_live_exec_policy_objective_verdict",
  "_live_exec_policy_objective_score",
  "_live_exec_policy_objective_constrained",
  "_live_exec_policy_recent_win_rate_guard_enabled",
  "_live_exec_policy_recent_win_rate_guard_period",
  "_live_exec_policy_recent_win_rate_guard_threshold",
  "_live_exec_policy_recent_win_rate_guard_scale",
  "_live_exec_policy_recent_win_rate_guard_min_realized_n",
  "_live_exec_policy_recent_win_rate_guard_win_rate",
  "_live_exec_policy_recent_win_rate_guard_realized_n",
  "_live_exec_policy_recent_win_rate_guard_alpha_ready",
  "_live_exec_policy_recent_win_rate_guard_evidence_status",
  "_live_exec_policy_recent_win_rate_guard_active",
  "_live_exec_policy_recent_win_rate_guard_reason",
  "_live_exec_policy_recent_win_rate_guard_scale_applied",
  "_live_exec_policy_recent_performance_guard_metric",
  "_live_exec_policy_recent_performance_guard_value",
  "_live_exec_policy_recent_performance_guard_threshold",
  "_live_exec_policy_recent_performance_guard_active",
  "_live_exec_policy_recent_performance_guard_reason",
  "_live_exec_policy_recent_performance_guard_scale_applied",
  "_live_exec_policy_scale_applied",
  "_live_exec_policy_scale",
  "_live_exec_policy_qty_before",
  "_live_exec_policy_qty_after",
]);

function extractLiveExecutionPolicyTrace(features = null) {
  if (!features || typeof features !== "object") return {};
  const out = {};
  for (const key of TRACE_KEYS) {
    if (features[key] !== undefined) out[key] = features[key];
  }
  return out;
}

function toLiveExecutionPolicyTopLevel(trace = null) {
  const src = trace && typeof trace === "object" ? trace : {};
  return {
    live_exec_policy_stage: src._live_exec_policy_stage ?? null,
    live_exec_policy_reason: src._live_exec_policy_reason ?? null,
    live_exec_policy_market: src._live_exec_policy_market ?? null,
    live_exec_policy_action: src._live_exec_policy_action ?? null,
    live_exec_policy_allocation_score: src._live_exec_policy_allocation_score ?? null,
    live_exec_policy_quarantine_reason: src._live_exec_policy_quarantine_reason ?? null,
    live_exec_policy_plan_status: src._live_exec_policy_plan_status ?? null,
    live_exec_policy_plan_mode: src._live_exec_policy_plan_mode ?? null,
    live_exec_policy_plan_global_scale: src._live_exec_policy_plan_global_scale ?? null,
    live_exec_policy_plan_market_scale: src._live_exec_policy_plan_market_scale ?? null,
    live_exec_policy_quality_latency_ms: src._live_exec_policy_quality_latency_ms ?? null,
    live_exec_policy_quality_partial_pct: src._live_exec_policy_quality_partial_pct ?? null,
    live_exec_policy_quality_slippage_bps: src._live_exec_policy_quality_slippage_bps ?? null,
    live_exec_policy_quality_global_status: src._live_exec_policy_quality_global_status ?? null,
    live_exec_policy_quality_global_latency_p95_ms: src._live_exec_policy_quality_global_latency_p95_ms ?? null,
    live_exec_policy_quality_global_partial_pct: src._live_exec_policy_quality_global_partial_pct ?? null,
    live_exec_policy_quality_global_slippage_p95_bps: src._live_exec_policy_quality_global_slippage_p95_bps ?? null,
    live_exec_policy_lineage_intents_signal_doc_id_null_rate: src._live_exec_policy_lineage_intents_signal_doc_id_null_rate ?? null,
    live_exec_policy_lineage_fills_signal_doc_id_null_rate: src._live_exec_policy_lineage_fills_signal_doc_id_null_rate ?? null,
    live_exec_policy_lineage_fills_intent_id_null_rate: src._live_exec_policy_lineage_fills_intent_id_null_rate ?? null,
    live_exec_policy_lineage_entry_fills_intent_id_null_rate: src._live_exec_policy_lineage_entry_fills_intent_id_null_rate ?? null,
    live_exec_policy_lineage_entry_fills_24h_n: src._live_exec_policy_lineage_entry_fills_24h_n ?? null,
    live_exec_policy_lineage_has_entry_fill_intent_metric: src._live_exec_policy_lineage_has_entry_fill_intent_metric ?? null,
    live_exec_policy_lineage_reason_suppressed: src._live_exec_policy_lineage_reason_suppressed ?? null,
    live_exec_policy_learning_epoch_exception_release_active: src._live_exec_policy_learning_epoch_exception_release_active ?? null,
    live_exec_policy_recent_win_rate_guard_enabled: src._live_exec_policy_recent_win_rate_guard_enabled ?? null,
    live_exec_policy_recent_win_rate_guard_period: src._live_exec_policy_recent_win_rate_guard_period ?? null,
    live_exec_policy_recent_win_rate_guard_threshold: src._live_exec_policy_recent_win_rate_guard_threshold ?? null,
    live_exec_policy_recent_win_rate_guard_scale: src._live_exec_policy_recent_win_rate_guard_scale ?? null,
    live_exec_policy_recent_win_rate_guard_min_realized_n: src._live_exec_policy_recent_win_rate_guard_min_realized_n ?? null,
    live_exec_policy_recent_win_rate_guard_win_rate: src._live_exec_policy_recent_win_rate_guard_win_rate ?? null,
    live_exec_policy_recent_win_rate_guard_realized_n: src._live_exec_policy_recent_win_rate_guard_realized_n ?? null,
    live_exec_policy_recent_win_rate_guard_alpha_ready: src._live_exec_policy_recent_win_rate_guard_alpha_ready ?? null,
    live_exec_policy_recent_win_rate_guard_evidence_status: src._live_exec_policy_recent_win_rate_guard_evidence_status ?? null,
    live_exec_policy_recent_win_rate_guard_active: src._live_exec_policy_recent_win_rate_guard_active ?? null,
    live_exec_policy_recent_win_rate_guard_reason: src._live_exec_policy_recent_win_rate_guard_reason ?? null,
    live_exec_policy_recent_win_rate_guard_scale_applied: src._live_exec_policy_recent_win_rate_guard_scale_applied ?? null,
    live_exec_policy_recent_performance_guard_metric: src._live_exec_policy_recent_performance_guard_metric ?? null,
    live_exec_policy_recent_performance_guard_value: src._live_exec_policy_recent_performance_guard_value ?? null,
    live_exec_policy_recent_performance_guard_threshold: src._live_exec_policy_recent_performance_guard_threshold ?? null,
    live_exec_policy_recent_performance_guard_active: src._live_exec_policy_recent_performance_guard_active ?? null,
    live_exec_policy_recent_performance_guard_reason: src._live_exec_policy_recent_performance_guard_reason ?? null,
    live_exec_policy_recent_performance_guard_scale_applied: src._live_exec_policy_recent_performance_guard_scale_applied ?? null,
    live_exec_policy_other_server_policy_watch_only_reasons: Array.isArray(src._live_exec_policy_other_server_policy_watch_only_reasons)
      ? src._live_exec_policy_other_server_policy_watch_only_reasons
      : null,
    live_exec_policy_blocked: typeof src._live_exec_policy_reason === "string"
      ? src._live_exec_policy_reason !== "LIVE_POLICY_OK"
      : null,
  };
}

module.exports = {
  TRACE_KEYS,
  extractLiveExecutionPolicyTrace,
  toLiveExecutionPolicyTopLevel,
};
